env: DEV
port: 3000
apps:
  JXT-NG:
    isActive: true
    regions:
      - NA
  ECT-NG:
    isActive: true
    regions:
      - EMEA
logsImagesInfo:
  baseDirectory: /home/vickykatoch/logs
  archiveInterval: 7d
  archiveTarget: /home/vickykatoch/logs/archive
dataInfo:
  dataPath: /home/vickykatoch/logs/data
  archiveInterval: 7d
  archiveTarget: /home/vickykatoch/logs/archive
instanceCount: 8
freeRoutes:
  - /home
