env: DEV
port: 3000
apps:
  JXT-NG:
    isActive: true
    regions:
      - NA
  ECT-NG:
    isActive: true
    regions:
      - EMEA
logsImagesInfo:
  baseDirectory: C:\Users\vicky\logs
  archiveInterval: 7d
  archiveTarget: C:\Users\vicky\logs\archive
dataInfo:
  transdbPath: C:\Users\vicky\logs\data
  usersdbPath: C:\Users\vicky\logs\data
  archiveInterval: 7d
  archiveTarget: C:\Users\vicky\logs\archive
instanceCount: 8
