env: DEV
port: 3000
apps:
  JXT-NG:
    isActive: true
    regions:
      - NA
  ECT-NG:
    isActive: true
    regions:
      - EMEA
logsImagesInfo:
  baseDirectory: /Users/balwinderkatoch/volumes/logs
  archiveInterval: 7d
  archiveTarget: /Users/balwinderkatoch/volumes/archive
dataInfo:
  transdbPath: /Users/balwinderkatoch/volumes/data
  usersdbPath: /Users/balwinderkatoch/volumes/data
  archiveInterval: 7d
  archiveTarget: /Users/balwinderkatoch/volumes/archive
instanceCount: 8
